---
- name: Ensure git is installed
  hosts: localhost
  tasks:
  - apt:
      name: git
      state: latest

- name: Ensure ~/.gitconfig copied from files/master.gitconfig
  hosts: localhost
  tasks:
  - copy:
      src: "files/master.gitconfig"
      dest: "~/.gitconfig"

- name: Ensure mc is installed
  hosts: localhost
  become: yes
  tasks:
  - apt:
      name: mc
      state: latest
      update_cache: yes

- name: Ensure vim is installed
  hosts: localhost
  become: yes
  tasks:
  - apt:
      name: vim
      state: latest
      update_cache: yes
  - copy:
      src: "files/master.vimrc"  
      dest: "~/.vimrc"

- name: Ensure blender is installed for dependencies
  hosts: localhost
  become: yes
  tasks:
  - apt:
      name: blender
      state: latest

- name: Ensure blender is remomved
  hosts: localhost
  become: yes
  tasks:
  - apt:
      name: blender
      state: absent

- name: Ensure download blender278
  hosts: localhost
  tasks:
  - get_url:
      url: https://download.blender.org/release/Blender2.78/blender-2.78c-linux-glibc219-x86_64.tar.bz2
      dest: /tmp/blender278tar.gz

- name:  Extract /tmp/blender278.tar.bz in /opt/blender278
  hosts: localhost
  become: yes
  tasks:
  - ansible.builtin.unarchive:
      src: /tmp/blender278.tar.gz 
      dest: /opt/blender278/

- name: Create a symbolink link from /opt/blender278/blender to /usr/bin/blender278
  hosts: localhost
  become: yes
  tasks:
  - ansible.builtin.file:
      src: /opt/blender278/blender
      dest: /usr/bin/blender278
      owner: "{{ lookup('env', 'USR') }}"
      group: "{{ lookup('env', 'USR') }}"
      state: link
